export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const OPEN_MODAL_SCHOOL = "OPEN_MODAL_SCHOOL";
export const CLOSE_MODAL_SCHOOL = "CLOSE_MODAL_SCHOOL";
export const OPEN_MODAL_ABSTRACT = "OPEN_MODAL_ABSTRACT";
export const CLOSE_MODAL_ABSTRACT = "CLOSE_MODAL_ABSTRACT";
