export const FILLED_FORM_USER = "FILLED_FORM_USER";
export const CONTINUE_FORM = "CONTINUE_FORM";
export const FILLED_FORM_SCHOOL = "FILLED_FORM_SCHOOL";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_FAIL= "REGISTER_USER_FAIL";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";


